### ISSUE TITLE
[Mac OS X] Intelli J java.lang.RuntimeException

### ISSUE THREAD

**Issue by priverop** [krasa/VisualVMLauncher#19]
Hello,

I'm trying to get it work with IntelliJ IDEA CE (2017.2) in Mac OSX Sierra, I've configured the Path to the .jar, but when I execute it:

```
appId=103984236343073, jdkHome=null, visualVmHome=/Users/XXX/IdeaProjects/VisualVMLauncher.jar
java.lang.RuntimeException: appId=103984236343073, jdkHome=null, visualVmHome=/Users/XXX/IdeaProjects/VisualVMLauncher.jar
	at krasa.visualvm.VisualVMHelper.startVisualVM(VisualVMHelper.java:75)
	at krasa.visualvm.runner.RunVisualVMRunner.runVisualVM(RunVisualVMRunner.java:137)
	at krasa.visualvm.runner.RunVisualVMRunner.doExecute(RunVisualVMRunner.java:88)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.RunProfileStarter.executeAsync(RunProfileStarter.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl.lambda$startRunProfile$7(ExecutionManagerImpl.java:390)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:72)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: Cannot run program "/Users/XXX/IdeaProjects/VisualVMLauncher.jar": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at krasa.visualvm.VisualVMHelper.openInVisualVM(VisualVMHelper.java:130)
	at krasa.visualvm.VisualVMHelper.startVisualVM(VisualVMHelper.java:73)
	... 26 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 30 more
```

I can build and run the program as usual, so I'm not sure about this "jdkHome=null" thing...

Thanks!

**Comment by priverop** [comment]
Okay I just realized I needed to apply chmod to the VisualVMLauncher.jar

Sorry!!

(I changed the title so It's easier to people to find it on google)
